### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by KK4ito** [z3r0privacy/ALGD2_Graph#1]
Check my comments at sourceCode (marked with XXX:)

f826352bd9e1ecd07a3d491f7125971bb1c40140
10512883a7ef8b6571bb033dad78fb69803a34b0

**Comment by z3r0privacy** [comment]
Looks good. Commented my changes with XXX
Added a view basic functionallities we forgot earlier today ;)
m_vertexCounter isn't needed in Graph class. The map count the vertexes for us :D
